server:
  port: 9999

spring:
  aplication:
    name: desafiocompassouol

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate: org.hibernate.dialect.MySQL8Dialect
    jmx:
      enable:false
    datasource:
      url: jbdc:mysql://localhost:3306/desafiocompassouol?allowPublicKeyRetrieval=true&sslMode=DISABLED
      username: root
      password: 123

